servers:
    type: rest
    resource: FormaLibre\RestBundle\Controller\ServerController

platforms:
    type: rest
    resource: FormaLibre\RestBundle\Controller\PlatformController

clients:
    type: rest
    resource: FormaLibre\RestBundle\Controller\ClientController
